server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 指定环境
  profiles:
    active: dev
  # 应用重命名
  application:
    name: Ai-TetoSoup
  # 数据库配置
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}

# AI接口
ai:
  apiKey: ${sky.ai.apikey}

# 接口文档
knife4j:
  enable: true
  openapi:
    title: Teto的接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.rngad33.tetosoup.controller
